# Use the official python image from the dockerhub
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Install FastAPI and other dependencies
COPY ./app/requirements.txt /app/requirements.txt
RUN pip install -r /app/requirements.txt

# Copy the FastAPI app code into the container
COPY ./app /app

# Copy the static files into the container
COPY ./static /app/static

# Run the FastAPI app with Uvicorn
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]
