version: '3.8'

services:
    tonutils-storage:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '127.0.0.1:8080:8080'
            - '127.0.0.1:17555:17555/udp'
        volumes:
            - ./tonutils-storage-db:/tonutils-storage-db
            - ./files:/files

    fastapi:
        build:
            context: .
            dockerfile: Dockerfile.fastapi
        ports:
            - '127.0.0.1:80:80'
        volumes:
            - ./files:/files
        depends_on:
            - tonutils-storage

    reverse-proxy:
        build:
            context: .
            dockerfile: Dockerfile.reverse-proxy
        network_mode: 'host'
        volumes:
            - ./reverse-proxy-config:/reverse-proxy
        depends_on:
            - fastapi
